### ISSUE TITLE
video are not avaliable

### ISSUE THREAD

**Issue by jackchen69** [freearhey/face-extractor#6]
don't know why can't preprocess video. mp4.

such as video has 5 seconds. but it is not working

Traceback (most recent call last):
  File "extract.py", line 125, in <module>
    main(args)
  File "extract.py", line 74, in main
    results = RetinaFace.detect_faces(image["source"])
  File "/homes/jl007/.conda/envs/face/lib/python3.7/site-packages/retinaface/RetinaFace.py", line 63, in detect_faces
    img = get_image(img_path)
  File "/homes/jl007/.conda/envs/face/lib/python3.7/site-packages/retinaface/RetinaFace.py", line 53, in get_image
    if len(img.shape) != 3 or np.prod(img.shape) == 0:
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by freearhey** [comment]
fixed
